inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_inspect # default

Metrics/BlockLength:
  Exclude:
    - spec/**/*
